- name: add IPv4 address gitlab
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ ansible_host }}$'
    line: "{{ ansible_host }} gitlab.local"
    state: present
  tags:
    - gitlab

- name: add the GitLab package repository and install the package
  get_url:  
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest: "/opt/script.deb.sh"
    mode: 755
  tags:
    - gitlab
    
- name: Execute the script.deb.sh
  shell: /opt/script.deb.sh
  tags:
    - gitlab

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - gitlab

- name: install required nano package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl 
    - openssh-server 
    - ca-certificates 
    - apt-transport-https 
    - perl
    - debian-archive-keyring
    - gnupg
  tags:
    - gitlab

- name: adding gpg keys for gitlab-ce
  ansible.builtin.apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    state: present
  tags:
    - gitlab

- name: create a new apt list file
  ansible.builtin.blockinfile:
    dest: "/etc/apt/sources.list.d/gitlab_gitlab-ce.list"
    block: |
      deb https://packages.gitlab.com/gitlab/gitlab-ce/debian/ buster main
      deb-src https://packages.gitlab.com/gitlab/gitlab-ce/debian/ buster main
  tags:
    - gitlab

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - gitlab

- name: install gitlab-ce
  package:
    name: gitlab-ce
    state: present
  environment:
    EXTERNAL_URL: "http://gitlab.local"
  tags:
    - gitlab
    - install-gitlab

- name: setup /etc/gitlab/gitlab.rb
  ansible.builtin.blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: |
      prometheus['enable'] = false
      alertmanager['enable'] = false
      node_exporter['enable'] = false
      postgres_exporter['listen_address'] = '{{ ansible_host }}:9187'
      redis_exporter['listen_address'] = '{{ ansible_host }}:9121'
      gitlab_exporter['listen_address'] = '{{ ansible_host }}'
      gitlab_exporter['listen_port'] = '9168'
      sidekiq['listen_address'] = "{{ ansible_host }}"
      sidekiq['listen_port'] = 8082

  tags:
    - gitlab-reconfigure
    - gitlab
    - install-gitlab

- name: gitlab-ctl reconfigure
  command: gitlab-ctl reconfigure
  tags:
    - gitlab-reconfigure
    - gitlab
    - install-gitlab

# TODO: pi@rpi-4-8gb-0 ~ $ sudo gitlab-backup create SKIP=tar

