---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - rpi-update

- hosts: gitlab
  gather_facts: yes
  become: yes
  roles:
    - gitlab

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - k3s
