---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - rpi-update

- hosts: gitlab
  gather_facts: yes
  become: yes
  roles:
    - gitlab

- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - nfs

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - k3s

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - k3s-gitlab-runners
