- name: install required nano package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-kernel-server
    - rpcbind
  tags:
    - nfs

- name: Creates directory /opt/nfs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/nfs
  tags:
    - nfs

- name: mount segragate disk
  ansible.posix.mount:
    path: /opt/nfs
    src: PARTUUID={{ segragete_partuuid }} 
    fstype: ntfs
    opts: defaults,noatime,nodiratime 
    state: mounted
  tags:
    - nfs

- name: Creates directory /opt/nfs/mac-backups
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/nfs/mac-backups
    - /opt/nfs/longhorn
    - /opt/nfs/gitlab-baremetal
  tags:
    - nfs

- name: make entry in /etc/exports
  blockinfile:
    path: /etc/exports
    state: present
    block: |
      /opt/nfs/mac-backups *(rw,sync,no_subtree_check,no_root_squash)
      /opt/nfs/longhorn *(rw,sync,no_subtree_check,no_root_squash)
      /opt/nfs/gitlab-baremetal *(rw,sync,no_subtree_check,no_root_squash)
  tags:
    - nfs

- name: restart nfs-kernel-server
  service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  with_items:
    - nfs-server
    - nfs-kernel-server
    - rpc-statd
  tags:
    - nfs

- name: exportfs -ar
  command: exportfs -ar
  tags:
    - nfs

