- name: add helm chart repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  with_items:
    - { name: 'grafana', url: 'https://grafana.github.io/helm-charts' }
    - { name: 'nginx', url: 'https://kubernetes.github.io/ingress-nginx' }
    - { name: 'prometheus', url: 'https://prometheus-community.github.io/helm-charts'}
    - { name: 'longhorn', url: 'https://charts.longhorn.io'}
  tags:
    - helm
    - helm-repos

- name: install pip deps
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - kubernetes
  tags:
    - prometheus-secret

- name: copy k8s ingress patch files
  copy:
    src: '{{ item }}'
    dest: '/opt/{{ item }}'
  with_items:
    - grafana-ing.patch
    - prometheus-ing.patch
    - longhorn-ing.patch
  tags:
    - helm
    - longhorn-patch
    - longhorn-deployment

- name: deploy nginx ingress controller
  kubernetes.core.helm:
    name: nginx-ingress
    chart_ref: nginx/ingress-nginx
    release_namespace: default
    create_namespace: true
    release_state: present
    values:
      controller:
        service:
            nodePorts:
                http: "30111"
                https: "30222"
  tags:
    - nginx
    - helm
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: deploy grafana
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: default
    create_namespace: true
    release_state: present
    values:
      ingress:
        enabled: true
        path: /grafana/?(.*)
        hosts:
          - raspberrypi
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          nginx.ingress.kubernetes.io/use-regex: "true"
          kubernetes.io/ingress.class: nginx
      grafana.ini:
        server:
          root_url: "%(protocol)s://%(domain)s/grafana"
          serve_from_sub_path: true
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: PrometheusRaspberryPiHomeLab
            type: prometheus
            url: http://prometheus-server/prometheus
      dashboards:
         default:
           monitoring:
             gnetId:  15120
             revision: 11
             datasource: PrometheusRaspberryPiHomeLab 
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: 'default'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards
      persistence:
        type: pvc
        enabled: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 1Gi
  tags:
    - helm
    - grafana
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: patch grafana ingress
  command: kubectl patch ingress grafana --patch-file /opt/grafana-ing.patch
  tags:
    - helm
    - grafana-patch
    - grafana
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: generate prometeus basic auth secret
  shell: htpasswd -nb "{{ prometheus_user }}" "{{ prometheus_pass }}" | base64
  register: _prometheus_basic_auth
  tags:
    - helm
    - prometheus
    - prometheus-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: create basic auth k8s secret for Prometheus
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      type: Opaque             
      metadata:
        name: prometheus-basic-auth
        namespace: default    
      data:
        auth: "{{ _prometheus_basic_auth.stdout }}"
  tags:
    - helm
    - prometheus
    - prometheus-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: deploy prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus/prometheus
    release_namespace: default
    create_namespace: true
    release_state: present
    values:
      alertmanager:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      prometheus-node-exporter:
        enabled: false
      server:
        ingress:
          enabled: true
          path: /prometheus
          hosts:
            - raspberrypi
          annotations:
            nginx.ingress.kubernetes.io/use-regex: "true"
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/auth-realm: Authentication Required
            nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
            nginx.ingress.kubernetes.io/auth-type: basic
        prefixURL: /prometheus
        extraFlags:
          - web.enable-lifecycle
          - web.external-url=/prometheus
        persistentVolume:
          enabled: true
          storageClass: longhorn
          size: 2Gi
  tags:
    - helm
    - prometheus
    - prometheus-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: patch prometheus ingress
  command: kubectl patch ingress prometheus-server --patch-file /opt/prometheus-ing.patch
  tags:
    - helm
    - prometheus-patch
    - prometheus-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: generate longhorn basic auth secret
  shell: htpasswd -nb "{{ longhorn_user }}" "{{ longhorn_pass }}" | base64
  register: _longhorn_basic_auth
  tags:
    - helm
    - longhorn
    - longhorn-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: create basic auth k8s secret for longhorn
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      type: Opaque             
      metadata:
        name: longhorn-basic-auth
        namespace: longhorn-system    
      data:
        auth: "{{ _longhorn_basic_auth.stdout }}"
  tags:
    - helm
    - longhorn
    - longhorn-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    release_state: present
    values:
      csi:
        attacherReplicaCount: 1
        provisionerReplicaCount: 1
        resizerReplicaCount: 1
        snapshotterReplicaCount: 1
      defaultSettings:
        concurrentReplicaRebuildPerNodeLimit: 2
        defaultReplicaCount: 1
        guaranteedEngineManagerCPU: 4
        guaranteedReplicaManagerCPU: 4
      image:
        defaultImage: true
      longhorn:
        default_setting: true
      persistence:
        defaultClass: true
        defaultFsType: ext4
        defaultClassReplicaCount: 2
        defaultDataLocality: disabled # best-effort otherwise
        reclaimPolicy: Retain
      ingress:
      ## Set to true to enable ingress record generation
        enabled: true
        host: raspberrypi
        path: /longhorn(/|$)(.*)
        annotations:
            # nginx.ingress.kubernetes.io/use-regex: "true"
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /$2
            nginx.ingress.kubernetes.io/auth-realm: Authentication Required
            nginx.ingress.kubernetes.io/auth-secret: longhorn-basic-auth
            nginx.ingress.kubernetes.io/auth-type: basic
  tags:
    - longhorn
    - longhorn-deployment
    - longhorn-secret
    - helm
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

- name: patch longhorn ingress
  command: kubectl patch ingress longhorn-ingress --patch-file /opt/longhorn-ing.patch -n longhorn-system
  tags:
    - helm
    - longhorn-patch
    - longhorn-deployment
    - longhorn-secret
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
